#!/bin/bash

set -eux

if [ $UID -ne 0 ]; then
  echo "ERROR: Must be run as root!" >&2
  exit 1
fi

TMP_DIR=$(mktemp -d /tmp/packer-XXXX)

clean() {
  echo 'Unmounting image...'
  umount -f "$TMP_DIR"
  rmdir --ignore-fail-on-non-empty "$TMP_DIR"
}

trap clean EXIT

echo 'Mounting root partition...'
mount "${NBD}p1" "$TMP_DIR"

echo 'Copying vmlinuz...'
mkdir -p ./kernels/
find "$TMP_DIR/boot/" -name "vmlinuz-*" -type f -exec cp {} ./kernels/ \;
