# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
  "manager0" => "192.168.77.10",
  "worker0" => "192.168.77.11",
}

Vagrant.configure("2") do |config|
  config.vm.provider "libvirt"
  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa_smoke_test.pub").first.strip

  hosts.each do |name, ip|
    config.vm.define name do |machine|
      machine.vm.box = "generic/rocky9"
      machine.vm.network "private_network", ip: ip
      config.vm.provision "shell" do |s|
        s.inline = <<-SHELL
          mkdir -p ~/.ssh && touch authorized_keys
          echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
          echo #{ssh_pub_key} >> /root/.ssh/authorized_keys
          systemctl stop firewalld
          systemctl disable firewalld
        SHELL
      end
    end
  end
end
