#!/bin/bash -eux

set -eux

if [ $UID -ne 0 ]; then
  echo "ERROR: Must be run as root!" >&2
  exit 1
fi

clean() {
  echo 'Unmounting image...'
  umount -f "$NFS_DIR"
  rmdir --ignore-fail-on-non-empty "$NFS_DIR"
  umount -f "$TMP_DIR"
  rmdir --ignore-fail-on-non-empty "$TMP_DIR"
}

trap clean EXIT

export MOUNT=${MOUNT:-"10.10.2.11:/mnt/pool1/k8s/xcat"}
export EXPORT_PATH=${EXPORT_PATH:-/install/netboot/rocky8.6/x86_64/compute/rootimg/}
NFS_DIR=$(mktemp -d /tmp/nfs-XXXX)
TMP_DIR=$(mktemp -d /tmp/packer-XXXX)

echo 'Mounting nfs'
mount -t nfs "$MOUNT" "$NFS_DIR"

echo 'Mounting root partition...'
mount "${NBD}p1" "$TMP_DIR"

echo "Content inside ${NFS_DIR}/${EXPORT_PATH}:"
ls -lah "${NFS_DIR}/${EXPORT_PATH}"

echo "Preview: rsync -avzP --delete $TMP_DIR/ ${NFS_DIR}/${EXPORT_PATH}"
read -rp "Correct (this may delete everything in that directory and subdirectories) (y/N)?" choice
case "$choice" in
y | Y) ;;
*) umount -f "$NFS_DIR" && exit 0 ;;
esac

rsync -avzP --delete "$TMP_DIR/" "${NFS_DIR}/${EXPORT_PATH}"
