#!/bin/bash -e

if [ $UID -ne 0 ]; then
  echo "ERROR: Must be run as root!" >&2
  exit 1
fi

TMP_DIR=$(mktemp -d /tmp/packer-maas-XXXX)

echo 'Mounting root partition...'
mount "${NBD}p1" "$TMP_DIR"

echo 'Copying vmlinuz...'
cp "$TMP_DIR/boot/vmlinuz-${KERNEL}" ./kernel

echo 'Unmounting image...'
umount "$TMP_DIR"
rmdir "$TMP_DIR"
