#!/bin/bash -e
#
# tar-root - Create a tar.gz from a binded /dev/nbd device
#
# Author: Lee Trager <lee.trager@canonical.com>
#
# Copyright (C) 2020-2021 Canonical
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

if [ $UID -ne 0 ]; then
    echo "ERROR: Must be run as root!" >&2
    exit 1
fi

export OUTPUT=${OUTPUT:-output.tar.gz}

TMP_DIR=$(mktemp -d /tmp/packer-XXXX)

echo 'Mounting root partition...'
mount "${NBD}p1" "$TMP_DIR"

echo "Creating tar.gz image $OUTPUT..."
tar -Sczpf "$OUTPUT" --acls --selinux --xattrs -C "$TMP_DIR" .

echo 'Unmounting image...'
umount "$TMP_DIR"
rmdir "$TMP_DIR"
