#!/bin/sh

BASEDIR="$(dirname $(realpath "$0"))"
PROJECTDIR="$BASEDIR/../"

. "${BASEDIR}/setup-env"

set -e

section "Fetch the config"
cfctl kubeconfig --config "${PROJECTDIR}/cfctl.yaml" >./kubeconfig
chmod 600 ./kubeconfig

export KUBECONFIG="${PROJECTDIR}/kubeconfig"

section "Deploy kubevirt (virtual machines deployments)"
# Updating is only supported to n-1 to n. Be warned.
# https://kubevirt.io/user-guide/operations/updating_and_deletion/
kubectl apply -k "${PROJECTDIR}/core/kubevirt/overlays/prod"

section "Wait for all deployments to be Available"
sleep 10
kubectl wait deployments --timeout=3600s --all --all-namespaces --for condition=Available

section "Deploy multus (multiple network interfaces support)"
kubectl apply -f https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset-thick-plugin.yml
kubectl apply -f "${PROJECTDIR}/core/cni/calico-network-attachment-definition.yaml"

section "Wait for all deployments to be Available"
sleep 10
kubectl wait deployments --timeout=3600s --all --all-namespaces --for condition=Available

section "Deploy sealed secrets"
"${PROJECTDIR}/core/sealed-secrets/install.sh"

section "Change CoreDNS prod configuration"
kubectl apply -k "${PROJECTDIR}/core/coredns/overlays/prod/"

section "Setup cert-manager issuers"
kubectl apply -f "${PROJECTDIR}/core/cert-manager/"

section "Setup Traefik dashboard and routes"
kubectl apply -k "${PROJECTDIR}/core/traefik-dashboard/"

section "Deploy Argo CD and setup argo-cd routes"
"${PROJECTDIR}/core/argo-cd/install.sh"
kubectl apply -k "${PROJECTDIR}/core/argo-cd/"

section "Wait for all deployments to be Available"
kubectl wait deployments --timeout=3600s --all --all-namespaces --for condition=Available

echo "Credentials for Argo CD are admin $(kubectl get secret -n argocd argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 --decode)"
echo "You must change these credentials on the first login!"

cat <<EOF
You can now deploy applications with Argo CD!

Prepare the Argo CD applications in the argo/ directory!
EOF
